"""initial

Revision ID: 493401e8ac22
Revises: 
Create Date: 2026-03-02 15:54:19.740538

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '493401e8ac22'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bairro', schema=None) as batch_op:
        batch_op.alter_column('nome_bairro',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)

    with op.batch_alter_table('condicao_pagamento', schema=None) as batch_op:
        batch_op.alter_column('id_empreendimento',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('sinal',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('mensais',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('intercaladas',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('habite_se',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.create_unique_constraint('uq_condicao_empreendimento_ordem', ['id_empreendimento', 'ordem'])

    with op.batch_alter_table('construtora', schema=None) as batch_op:
        batch_op.alter_column('nome_construtora',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)

    with op.batch_alter_table('empreendimento', schema=None) as batch_op:
        batch_op.alter_column('nome_empreendimento',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('id_construtora',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('id_bairro',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('endereco',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)

    with op.batch_alter_table('equipamento', schema=None) as batch_op:
        batch_op.alter_column('piscina',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('coworking',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('lavanderia',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('restaurante_bar',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('academia',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('pet_playground',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('salao_festas',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('sauna',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('minimarket',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('imovel', schema=None) as batch_op:
        batch_op.alter_column('pavimento',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('apartamento',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('qtd_quartos',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('vagas',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('posicao', schema=None) as batch_op:
        batch_op.alter_column('nome_posicao',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)

    with op.batch_alter_table('valores', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('atualizado_em',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.create_unique_constraint('uq_valor_imovel_mes', ['id_imovel', 'mes_referencia'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('valores', schema=None) as batch_op:
        batch_op.drop_constraint('uq_valor_imovel_mes', type_='unique')
        batch_op.alter_column('atualizado_em',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('posicao', schema=None) as batch_op:
        batch_op.alter_column('nome_posicao',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('imovel', schema=None) as batch_op:
        batch_op.alter_column('vagas',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('qtd_quartos',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('apartamento',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('pavimento',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('equipamento', schema=None) as batch_op:
        batch_op.alter_column('minimarket',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('sauna',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('salao_festas',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('pet_playground',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('academia',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('restaurante_bar',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('lavanderia',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('coworking',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('piscina',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('empreendimento', schema=None) as batch_op:
        batch_op.alter_column('endereco',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id_bairro',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('id_construtora',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('nome_empreendimento',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('construtora', schema=None) as batch_op:
        batch_op.alter_column('nome_construtora',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('condicao_pagamento', schema=None) as batch_op:
        batch_op.drop_constraint('uq_condicao_empreendimento_ordem', type_='unique')
        batch_op.alter_column('habite_se',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('intercaladas',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('mensais',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('sinal',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('id_empreendimento',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('bairro', schema=None) as batch_op:
        batch_op.alter_column('nome_bairro',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
